/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        warnaUtama: '#1a1a2e',
        warnaSekunder: '#16213e',
        warnaAksen: '#0f3460',
        warnaTombol: '#e94560',
        
        // Warna dari landing page baru
        "on-primary-fixed": "#00201a",
        "primary": "#006b5a",
        "tertiary-container": "#d9755d",
        "background": "#f5fbf7",
        "on-tertiary-container": "#541103",
        "surface-container-low": "#eff5f1",
        "outline": "#6d7a75",
        "tertiary-fixed": "#ffdad2",
        "inverse-on-surface": "#ecf2ee",
        "surface-bright": "#f5fbf7",
        "on-secondary-fixed-variant": "#3a4a48",
        "secondary-fixed-dim": "#b9cac7",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "surface-tint": "#006b5a",
        "on-tertiary-fixed": "#3d0700",
        "secondary": "#52615f",
        "surface-container-highest": "#dee4e0",
        "outline-variant": "#bccac4",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#005144",
        "surface-variant": "#dee4e0",
        "tertiary": "#9a4430",
        "on-surface-variant": "#3d4945",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#7b2e1b",
        "surface-container-high": "#e4e9e6",
        "primary-fixed": "#80f7dc",
        "primary-container": "#14a38b",
        "surface-container": "#e9efec",
        "on-surface": "#171d1b",
        "secondary-fixed": "#d5e6e3",
        "inverse-surface": "#2c3230",
        "secondary-container": "#d5e6e3",
        "on-primary-container": "#003028",
        "tertiary-fixed-dim": "#ffb4a3",
        "on-secondary-container": "#586765",
        "error-container": "#ffdad6",
        "inverse-primary": "#62dac0",
        "surface-dim": "#d5dbd8",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#62dac0",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#0f1e1d",
        "surface-container-lowest": "#ffffff",
        "surface": "#f5fbf7",
        "on-background": "#171d1b",
        "brand-tosca-light": "#E6F7F4"
      },
      borderRadius: {
        "xl": "16px",
      },
      spacing: {
        "sm": "12px",
        "xs": "4px",
        "md": "16px",
        "margin-desktop": "48px",
        "base": "8px",
        "lg": "24px",
        "margin-mobile": "16px",
        "xl": "32px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "title-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
